name: Manual Mob Madness

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run MobSF
        run: |
          ApkDir="build/app/outputs/flutter-apk/"
          apk="app-release.apk"
          docker pull opensecurity/mobile-security-framework-mobsf
          docker run -itd -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest 
          cd $ApkDir
          ls -al
          wget http://localhost:8000/api_docs
          MOBSF_API_KEY=$(grep 'REST API Key' api_docs)
          MOBSF_API_KEY=${MOBSF_API_KEY:42:64}
          rm api_docs
          HASH=$(md5sum $apk)
          HASH=${HASH:0:32}
          curl -F "file=@$apk" http://localhost:8000/api/v1/upload -H "Authorization:$MOBSF_API_KEY"
          curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=$apk&hash=$HASH" -H "Authorization:$MOBSF_API_KEY"
          curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=$HASH" -H "Authorization:$MOBSF_API_KEY" --output ${{ steps.build_id.outputs.id }}-security-scan.pdf
          ls -al
          
          echo "Generalize upload-artifact using static directory"
          mkdir -p upload
          cp ./-security-scan.pdf upload/ || cp -- -security-scan.pdf upload/
          pwd
          ls -al
          cd upload
          echo "Going into upload directory"
          pwd
          ls -al
          cd /home/runner/work/flutter-webview/flutter-webview/build/app/outputs/flutter-apk/

      - name: Upload Security Report
        uses: actions/upload-artifact@v2
        with:
         name: upload
         path: build/app/outputs/flutter-apk/upload/-security-scan.pdf
